# Generated by Django 5.0.1 on 2024-01-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('tipo', models.CharField(max_length=60)),
                ('edadRecomendada', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Libros',
            },
        ),
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('socio', models.IntegerField()),
                ('activo', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Socios',
                'ordering': ['apellido'],
            },
        ),
    ]
